spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rto_db?currentSchema=public&sslmode=disable
    username: rto_app_admin
    password: ${db-password}
server:
  port: 8081
  servlet:
    session:
      cookie:
        httpOnly: true
        sameSite: NONE
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: 'health,info,env,beans,metrics'
message-service:
  host: ${MESSAGESERVICE_HOST}
  api-key: ${MESSAGESERVICE_APIKEY}
  license-number: ${MESSAGESERVICE_LICENSENUMBER}